import puppeteer from 'puppeteer';
import http from 'http';
import fs from 'fs';
import path from 'path';
const root = '/Users/jovan/Work/micromachines';
const srv = http.createServer((req, res) => {
  let p = decodeURIComponent(new URL(req.url, 'http://x').pathname);
  if (p === '/') p = '/index.html';
  const M = { '.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css' };
  fs.readFile(path.join(root, p), (e, d) => { if (e) { res.writeHead(404); res.end(); } else { res.writeHead(200, { 'Content-Type': M[path.extname(p)] || 'text/plain' }); res.end(d); } });
}).listen(8688);
const browser = await puppeteer.launch({ headless: true, args: ['--no-sandbox', '--use-gl=angle', '--enable-unsafe-swiftshader'] });
const page = await browser.newPage();
await page.setViewport({ width: 1280, height: 800 });
page.on('pageerror', e => console.log('[PAGE ERROR]', e.message));
await page.goto('http://localhost:8688/', { waitUntil: 'networkidle0' });
await new Promise(r => setTimeout(r, 700));
await page.evaluate(() => window.__MM.startRace(1, true));   // breakfast with autopilot
await page.evaluate(() => window.__MM.setTimeScale(6));
await page.waitForFunction(() => window.__MM.state() === 'finished', { timeout: 90000 });
await page.evaluate(() => window.__MM.setTimeScale(1));
await new Promise(r => setTimeout(r, 500));
await page.click('#btn-results-car');
await new Promise(r => setTimeout(r, 1000));
console.log('state:', await page.evaluate(() => window.__MM.state()));
await page.screenshot({ path: 'shots/changecar.png' });
await page.click('#car-next');
await new Promise(r => setTimeout(r, 400));
await page.click('#btn-car-race');
await new Promise(r => setTimeout(r, 500));
console.log('after race btn:', await page.evaluate(() => window.__MM.state()), 'vehicle:', await page.evaluate(() => window.__MM.game.race.player.vehicle.id));
await browser.close(); srv.close(); process.exit(0);
